In [3]:

import os
import numpy as np
import pickle

fit_results = pickle.load(open('test_model.gz'))


[[[ 0.          0.        ]
  [ 0.          0.        ]]

 [[ 0.08333333  0.08333333]
  [ 0.08333333  0.08333333]]

 [[ 0.08333333  0.08333333]
  [ 0.08333333  0.08333333]]

 [[ 0.08333333  0.08333333]
  [ 0.08333333  0.08333333]]

 [[ 0.          0.        ]
  [ 0.          0.        ]]

 [[ 0.          0.        ]
  [ 0.          0.        ]]

 [[ 0.          0.        ]
  [ 0.          0.        ]]

 [[ 0.          0.        ]
  [ 0.          0.        ]]

 [[ 0.          0.        ]
  [ 0.          0.        ]]

 [[ 0.          0.        ]
  [ 0.          0.        ]]

 [[ 0.          0.        ]
  [ 0.          0.        ]]

 [[ 0.          0.        ]
  [ 0.          0.        ]]

 [[ 0.          0.        ]
  [ 0.          0.        ]]

 [[ 0.          0.        ]
  [ 0.          0.        ]]

 [[ 0.          0.        ]
  [ 0.          0.        ]]

 [[ 0.          0.        ]
  [ 0.          0.        ]]

 [[ 0.          0.        ]
  [ 0.          0.        ]]

 [[ 0.        

In [4]:

script_directory = '/Users/amcphers/Projects/remixt/remixt/tests/'
experiment_filename = os.path.join(script_directory, 'test_experiment.pickle')
with open(experiment_filename) as experiment_file:
    experiment = pickle.load(experiment_file)


In [8]:

import remixt.analysis.experiment

h = fit_results['h']
cn = fit_results['cn']
brk_cn = fit_results['brk_cn']

cn_table = remixt.analysis.experiment.create_cn_table(experiment, cn, h)
brk_cn_table = remixt.analysis.experiment.create_brk_cn_table(experiment, brk_cn)

brk_cn_table

n_1  side_1   n_2  side_2  cn_0  cn_1  cn_2 chromosome_1 chromosome_2  \
0   4842       1  4868       0     0     0     0           19           19   
1    651       1  3765       0     0     0     0            2           12   
2   4746       0  4843       1     0     0     0           19           19   
3   2432       0  2668       1     0     0     0            7            7   
4   1042       0  2183       1     0     0     0            2            6   
5    604       1   924       0     0     0     0            2            2   
6   1985       0  2094       1     0     0     1            5            5   
7    760       1  2218       0     0     0     0            2            6   
8   4734       1  4790       0     0     0     0           19           19   
9    761       0  2217       1     0     0     0            2            6   
10  1185       0  2435       1     0     0     0            3            7   
11   185       0   436       1     0     0     0            1            1   
12  1133       1  3495       0     0     0     0            3           11   
13  4352       0  4385       1     0     0     0           16           16   
14   138       1   524       0     0     0     1            1            1   
15    48       1   304       0     0     1     0            1            1   
16  2733       0  2738       1     0     0     0            8            8   
17  3024       1  3137       0     0     0     0            9            9   
18   233       0  4509       0     0     0     0            1           17   
19   232       1  4508       1     0     0     0            1           17   
20  4070       1  4225       1     0     0     0           14           15   
21  3675       1  3695       0     0     0     0           12           12   
22  3512       0  3562       1     0     0     0           11           11   
23   305       0   506       1     0     0     0            1            1   
24  1833       0  2010       1     0     0     0            5            5   
25  4786       1  4788       0     0     0     0           19           19   
26    27       1   560       0     0     0     0            1            1   
27  1184       1  2436       0     0     0     0            3            7   
28   481       0   551       1     0     0     0            1            1   
29  1090       0  1375       1     0     0     0            3            3   
30  2540       1  2663       0     0     0     0            7            7   
31  2281       1  2296       0     0     0     0            6            6   
32  1162       1  1202       0     0     0     0            3            3   
33  1857       1  1991       0     0     0     0            5            5   
34   300       0  2481       1     0     0     0            7            1   
35  2751       0  2936       1     0     0     0            8            8   
36  1134       0  3494       1     0     0     0           11            3   
37  1837       1  2808       1     0     0     0            8            5   
38  3491       1  3570       0     0     0     0           11           11   
39  3434       0  3613       1     0     0     0           11           11   
40  3007       1  3107       0     0     0     0            9            9   
41  1012       1  3331       0     0     0     0           10            2   
42  2025       1  2049       0     0     0     0            5            5   
43   773       0  3779       1     0     0     0           12            2   
44  4492       0  4527       1     0     0     0           17           17   
45  2062       0  2961       0     0     0     0            8            5   
46  4625       1  4699       0     0     0     0           18           18   
47  2465       0  2510       1     0     0     0            7            7   
48   733       0  1046       1     0     0     0            2            2   
49  1965       0  2104       1     0     0     0            5            5   
50  3338       1  3387     

In [6]:

selected_brk = frozenset({(4746, 0), (4843, 1)})
fit_results['model'].breakpoints.index(frozenset({(4746, 0), (4843, 1)}))

a1 = fit_results['model'].seg_fwd_remap[4745]
a2 = fit_results['model'].seg_fwd_remap[4746]

b1 = fit_results['model'].seg_fwd_remap[4843]
b2 = fit_results['model'].seg_fwd_remap[4844]


In [36]:

print np.where(np.asarray(fit_results['model'].model.posterior_marginals)[a1] > 0.25)
print np.where(np.asarray(fit_results['model'].model.posterior_marginals)[a2] > 0.25)


(array([90]),)
(array([99]),)


In [37]:

print np.asarray(fit_results['model'].model.cn_states)[54]
print np.asarray(fit_results['model'].model.cn_states)[90]

print np.asarray(fit_results['model'].model.cn_states)[99]
print np.asarray(fit_results['model'].model.cn_states)[101]


[[1 1]
 [1 2]
 [1 1]]
[[1 1]
 [2 1]
 [1 1]]
[[1 1]
 [2 2]
 [1 2]]
[[1 1]
 [2 2]
 [2 1]]


In [38]:

print np.where(np.asarray(fit_results['model'].model.posterior_marginals)[b1] > 0.25)
print np.where(np.asarray(fit_results['model'].model.posterior_marginals)[b2] > 0.25)


(array([93]),)
(array([85]),)


In [39]:

print np.asarray(fit_results['model'].model.cn_states)[55]
print np.asarray(fit_results['model'].model.cn_states)[93]

print np.asarray(fit_results['model'].model.cn_states)[11]
print np.asarray(fit_results['model'].model.cn_states)[85]


[[1 1]
 [1 2]
 [1 2]]
[[1 1]
 [2 1]
 [2 1]]
[[1 1]
 [0 2]
 [0 2]]
[[1 1]
 [2 0]
 [2 0]]


In [40]:

print np.where(np.asarray(fit_results['model'].model.joint_posterior_marginals)[a1] > 0.24)


(array([90]), array([99]))


In [41]:

np.where(np.asarray(fit_results['model'].model.p_breakpoint)[8].sum(axis=(1, 2)) > 0.24)


(array([3]),)

In [42]:

print np.asarray(fit_results['model'].model.brk_states)[[0, 1, 2, 3]]


[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]]


In [34]:

model = fit_results['model'].model

state_sequence = np.zeros((model.num_segments,), dtype=np.int64)
allele_state_prob = np.zeros((model.num_alleles, model.num_alleles))
allele_states = np.zeros((2,), dtype=np.int64)
new_p_breakpoint = np.zeros((model.num_breakpoints, model.num_brk_states, model.num_alleles, model.num_alleles))

def _argmax2(values, indices):
    vmax = values.min() - 1.
    indices[0] = 0
    indices[1] = 0
    for i in range(values.shape[0]):
        for j in range(values.shape[1]):
            if values[i, j] > vmax:
                vmax = values[i, j]
                indices[0] = i
                indices[1] = j

for k in range(model.num_breakpoints):
    allele_state_prob[:] = 0.
    for s_b in range(model.num_brk_states):
        for v_1 in range(2):
            for v_2 in range(2):
                allele_state_prob[v_1, v_2] += model.p_breakpoint[k, s_b, v_1, v_2]

    _argmax2(allele_state_prob, allele_states)

    for s_b in range(model.num_brk_states):
        for v_1 in range(2):
            for v_2 in range(2):
                new_p_breakpoint[k, s_b, allele_states[0], allele_states[1]] += model.p_breakpoint[k, s_b, v_1, v_2]

model.p_breakpoint = new_p_breakpoint



In [35]:

model.update_p_cn()
model.update_p_breakpoint()
